name: Python application test with Github Actions
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup on Python 3.12
      uses: actions/setup-python@v1
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: |
        make install_azure
    - name: Lint with Python
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
